// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

public final class EdgeType {
  private EdgeType() { }
  public static final int HIGHWAY = 0;
  public static final int ENTER_TIME_EXPANDED_NETWORK = 1;
  public static final int LEAVE_TIME_EXPANDED_NETWORK = 2;
  public static final int ENTER_PT = 3;
  public static final int EXIT_PT = 4;
  public static final int HOP = 5;
  public static final int DWELL = 6;
  public static final int BOARD = 7;
  public static final int ALIGHT = 8;
  public static final int OVERNIGHT = 9;
  public static final int TRANSFER = 10;
  public static final int WAIT = 11;
  public static final int WAIT_ARRIVAL = 12;

  public static final String[] names = { "HIGHWAY", "ENTER_TIME_EXPANDED_NETWORK", "LEAVE_TIME_EXPANDED_NETWORK", "ENTER_PT", "EXIT_PT", "HOP", "DWELL", "BOARD", "ALIGHT", "OVERNIGHT", "TRANSFER", "WAIT", "WAIT_ARRIVAL", };

  public static String name(int e) { return names[e]; }
}

