// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Edge extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Edge getRootAsEdge(ByteBuffer _bb) { return getRootAsEdge(_bb, new Edge()); }
  public static Edge getRootAsEdge(ByteBuffer _bb, Edge obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Edge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int time() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public MyGame.Sample.Validity validity() { return validity(new MyGame.Sample.Validity()); }
  public MyGame.Sample.Validity validity(MyGame.Sample.Validity obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int routeType() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public MyGame.Sample.FeedIdWithTimezone feedIdWithTimezone() { return feedIdWithTimezone(new MyGame.Sample.FeedIdWithTimezone()); }
  public MyGame.Sample.FeedIdWithTimezone feedIdWithTimezone(MyGame.Sample.FeedIdWithTimezone obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int transfers() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int stopSequence() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int tripDescriptor(int j) { int o = __offset(18); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int tripDescriptorLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector tripDescriptorVector() { return tripDescriptorVector(new ByteVector()); }
  public ByteVector tripDescriptorVector(ByteVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer tripDescriptorAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer tripDescriptorInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public MyGame.Sample.PlatformDescriptor platformDescriptor() { return platformDescriptor(new MyGame.Sample.PlatformDescriptor()); }
  public MyGame.Sample.PlatformDescriptor platformDescriptor(MyGame.Sample.PlatformDescriptor obj) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createEdge(FlatBufferBuilder builder,
      byte type,
      int time,
      int validityOffset,
      int route_type,
      int feed_id_with_timezoneOffset,
      int transfers,
      int stop_sequence,
      int trip_descriptorOffset,
      int platform_descriptorOffset) {
    builder.startTable(9);
    Edge.addPlatformDescriptor(builder, platform_descriptorOffset);
    Edge.addTripDescriptor(builder, trip_descriptorOffset);
    Edge.addStopSequence(builder, stop_sequence);
    Edge.addTransfers(builder, transfers);
    Edge.addFeedIdWithTimezone(builder, feed_id_with_timezoneOffset);
    Edge.addRouteType(builder, route_type);
    Edge.addValidity(builder, validityOffset);
    Edge.addTime(builder, time);
    Edge.addType(builder, type);
    return Edge.endEdge(builder);
  }

  public static void startEdge(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static void addTime(FlatBufferBuilder builder, int time) { builder.addInt(1, time, 0); }
  public static void addValidity(FlatBufferBuilder builder, int validityOffset) { builder.addOffset(2, validityOffset, 0); }
  public static void addRouteType(FlatBufferBuilder builder, int routeType) { builder.addInt(3, routeType, 0); }
  public static void addFeedIdWithTimezone(FlatBufferBuilder builder, int feedIdWithTimezoneOffset) { builder.addOffset(4, feedIdWithTimezoneOffset, 0); }
  public static void addTransfers(FlatBufferBuilder builder, int transfers) { builder.addInt(5, transfers, 0); }
  public static void addStopSequence(FlatBufferBuilder builder, int stopSequence) { builder.addInt(6, stopSequence, 0); }
  public static void addTripDescriptor(FlatBufferBuilder builder, int tripDescriptorOffset) { builder.addOffset(7, tripDescriptorOffset, 0); }
  public static int createTripDescriptorVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createTripDescriptorVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startTripDescriptorVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addPlatformDescriptor(FlatBufferBuilder builder, int platformDescriptorOffset) { builder.addOffset(8, platformDescriptorOffset, 0); }
  public static int endEdge(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishEdgeBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedEdgeBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Edge get(int j) { return get(new Edge(), j); }
    public Edge get(Edge obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

