// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample;

public final class Type {
  private Type() { }
  public static final byte HIGHWAY = 0;
  public static final byte ENTER_TIME_EXPANDED_NETWORK = 1;
  public static final byte LEAVE_TIME_EXPANDED_NETWORK = 2;
  public static final byte ENTER_PT = 3;
  public static final byte EXIT_PT = 4;
  public static final byte HOP = 5;
  public static final byte DWELL = 6;
  public static final byte BOARD = 7;
  public static final byte ALIGHT = 8;
  public static final byte OVERNIGHT = 9;
  public static final byte TRANSFER = 10;
  public static final byte WAIT = 11;
  public static final byte WAIT_ARRIVAL = 12;

  public static final String[] names = { "HIGHWAY", "ENTER_TIME_EXPANDED_NETWORK", "LEAVE_TIME_EXPANDED_NETWORK", "ENTER_PT", "EXIT_PT", "HOP", "DWELL", "BOARD", "ALIGHT", "OVERNIGHT", "TRANSFER", "WAIT", "WAIT_ARRIVAL", };

  public static String name(int e) { return names[e]; }
}

