engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      # it's not yet available for Java :)
      - java
  pmd:
    enabled: true
ratings:
  paths:
  - "**.java"
exclude_paths:
- "web/src/main/webapp/"
- "**.js"