version: '{build}'
clone_depth: 3
image: Visual Studio 2019
environment:
  DOCKER_USER:
    secure: iC/lO9cyDWqfFa3YZzgkQg==
  DOCKER_PASS:
    secure: 9kYreBg7+ayysVSKa8QZrg==
branches:
  only:
    - master
install:
  - ps: >-
      & $env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
      
build_script:
  - ps: docker build ./ -t harelmazor/graphhopper:latest
deploy_script:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - ps: docker push harelmazor/graphhopper:latest
  - ps: docker tag harelmazor/graphhopper:latest harelmazor/graphhopper:"$env:APPVEYOR_REPO_TAG_NAME"
  - ps: docker push harelmazor/graphhopper:"$env:APPVEYOR_REPO_TAG_NAME"
deploy:
    on:
      APPVEYOR_REPO_TAG: true