version: '{build}'
clone_depth: 3
image: Visual Studio 2019
environment:
  DOCKER_USER:
    secure: iC/lO9cyDWqfFa3YZzgkQg==
  DOCKER_PASS:
    secure: 9kYreBg7+ayysVSKa8QZrg==
branches:
  only:
    - master
install:
  - ps: & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
  - cmd: docker version
build_script:
  - docker build ./ -t harelmazor/graphhopper:"$env:APPVEYOR_REPO_TAG_NAME" -t harelmazor/graphhopper:latest
deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push harelmazor/graphhopper:"$env:APPVEYOR_REPO_TAG_NAME"
  - docker push harelmazor/graphhopper:latest
deploy:
  - provider: Environment
    name: production
    on:
      APPVEYOR_REPO_TAG: true