/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.graphhopper.coll;

import com.graphhopper.coll.MapEntry;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class MapEntry_DiffblueTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: MapEntry */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 63 branch to line 64
   */

  @Test
  public void equalsInputNullOutputFalse() {

    // Arrange
    final MapEntry objectUnderTest = new MapEntry(null, null);
    final Object obj = null;

    // Act
    final boolean retval = objectUnderTest.equals(obj);

    // Assert result
    Assert.assertEquals(false, retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 82 branch to line 82
   *  - conditional line 83 branch to line 83
   */

  @Test
  public void hashCodeOutputPositive() {

    // Arrange
    final MapEntry objectUnderTest = new MapEntry(null, null);

    // Act
    final int retval = objectUnderTest.hashCode();

    // Assert result
    Assert.assertEquals(2527, retval);
  }
}
