/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.graphhopper.storage;

import static org.mockito.AdditionalMatchers.or;
import static org.mockito.Matchers.isA;
import static org.mockito.Matchers.isNull;
import static org.powermock.api.mockito.PowerMockito.mockStatic;

import com.diffblue.deeptestutils.Reflector;
import com.graphhopper.storage.DAType.MemRef;
import com.graphhopper.storage.DAType;
import com.graphhopper.util.Helper;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.lang.reflect.Array;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

@RunWith(PowerMockRunner.class)
public class DAType_DiffblueTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: DAType */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 79 branch to line 80
   */
  @PrepareForTest({Helper.class})
  @Test
  public void fromStringInputNotNullOutputIllegalArgumentException() throws Exception {

    // Setup mocks
    mockStatic(Helper.class);

    // Arrange
    final String dataAccess = "";
    PowerMockito.doReturn("UNSAFESYNC").when(Helper.class);
    Helper.toUpperCase(or(isA(String.class), isNull(String.class)));

    // Act
    thrown.expect(IllegalArgumentException.class);
    DAType.fromString(dataAccess);

    // Method is not expected to return due to exception thrown
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 79 branch to line 81
   *  - conditional line 81 branch to line 83
   *  - conditional line 83 branch to line 84
   */
  @PrepareForTest({Helper.class})
  @Test
  public void fromStringInputNotNullOutputNotNull() throws Exception {

    // Setup mocks
    mockStatic(Helper.class);

    // Arrange
    final String dataAccess = "";
    PowerMockito.doReturn("UNSAFEGISS").when(Helper.class);
    Helper.toUpperCase(or(isA(String.class), isNull(String.class)));

    // Act
    final DAType retval = DAType.fromString(dataAccess);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "allowWrites"));
    Assert.assertEquals(false, Reflector.getInstanceField(retval, "integ"));
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "storing"));
    Assert.assertEquals(MemRef.UNSAFE, retval.getMemRef());
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 79 branch to line 81
   *  - conditional line 81 branch to line 83
   *  - conditional line 83 branch to line 85
   *  - conditional line 85 branch to line 88
   */
  @PrepareForTest({Helper.class})
  @Test
  public void fromStringInputNotNullOutputNotNull2() throws Exception {

    // Setup mocks
    mockStatic(Helper.class);

    // Arrange
    final String dataAccess = "";
    PowerMockito.doReturn("ENSQVM]KQQ").when(Helper.class);
    Helper.toUpperCase(or(isA(String.class), isNull(String.class)));

    // Act
    final DAType retval = DAType.fromString(dataAccess);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "allowWrites"));
    Assert.assertEquals(false, Reflector.getInstanceField(retval, "integ"));
    Assert.assertEquals(false, Reflector.getInstanceField(retval, "storing"));
    Assert.assertEquals(MemRef.HEAP, retval.getMemRef());
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 79 branch to line 81
   *  - conditional line 81 branch to line 83
   *  - conditional line 83 branch to line 85
   *  - conditional line 85 branch to line 86
   */
  @PrepareForTest({Helper.class})
  @Test
  public void fromStringInputNotNullOutputNotNull3() throws Exception {

    // Setup mocks
    mockStatic(Helper.class);

    // Arrange
    final String dataAccess = "";
    PowerMockito.doReturn("ARAM_STORE").when(Helper.class);
    Helper.toUpperCase(or(isA(String.class), isNull(String.class)));

    // Act
    final DAType retval = DAType.fromString(dataAccess);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "allowWrites"));
    Assert.assertEquals(false, Reflector.getInstanceField(retval, "integ"));
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "storing"));
    Assert.assertEquals(MemRef.HEAP, retval.getMemRef());
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 79 branch to line 81
   *  - conditional line 81 branch to line 82
   */
  @PrepareForTest({Helper.class})
  @Test
  public void fromStringInputNullOutputNotNull() throws Exception {

    // Setup mocks
    mockStatic(Helper.class);

    // Arrange
    final String dataAccess = null;
    PowerMockito.doReturn("SMMUUUNSAFEMMMMMMMMMAPRRRRAM_STORESSSSSSSSSSSS").when(Helper.class);
    Helper.toUpperCase(or(isA(String.class), isNull(String.class)));

    // Act
    final DAType retval = DAType.fromString(dataAccess);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "allowWrites"));
    Assert.assertEquals(false, Reflector.getInstanceField(retval, "integ"));
    Assert.assertEquals(true, Reflector.getInstanceField(retval, "storing"));
    Assert.assertEquals(MemRef.MMAP, retval.getMemRef());
  }
}
