/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.graphhopper.storage;

import com.graphhopper.storage.VLongStorage;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class VLongStorage_DiffblueTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: VLongStorage */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 101 branch to line 101
   *  - conditional line 102 branch to line 105
   *  - conditional line 106 branch to line 106
   *  - conditional line 108 branch to line 109
   */

  @Test
  public void readVLongOutputZero() {

    // Arrange
    final byte[] byteArray = {(byte)-128, (byte)0};
    final VLongStorage objectUnderTest = new VLongStorage(byteArray);

    // Act
    final long retval = objectUnderTest.readVLong();

    // Assert result
    Assert.assertEquals(0L, retval);
  }
}
