// Generated by GraphHopper's CustomWeightingSourceGenerator - DO NOT EDIT.
// Semantics mirror the Janino runtime template of CustomModelParser (GraphHopper, Apache License 2.0).
// Register at app startup: GeneratedWeightingRegistry.register(customModel, Supplier { GeneratedCarCustomWeighting() })
package com.graphhopper.routing.weighting.custom.generate

import com.graphhopper.routing.ev.*
import com.graphhopper.routing.weighting.custom.CustomWeightingHelper
import com.graphhopper.storage.BaseGraph
import com.graphhopper.util.CustomModel
import com.graphhopper.util.EdgeIteratorState
import com.graphhopper.util.JsonFeature

class GeneratedCarCustomWeighting : CustomWeightingHelper() {
    private lateinit var car_access_enc: BooleanEncodedValue
    private lateinit var road_environment_enc: EnumEncodedValue<RoadEnvironment>
    private lateinit var ferry_speed_enc: DecimalEncodedValue
    private lateinit var car_average_speed_enc: DecimalEncodedValue
    private lateinit var max_speed_enc: DecimalEncodedValue

    override fun init(customModel: CustomModel?, lookup: EncodedValueLookup?, areas: Map<String, JsonFeature>?) {
        super.init(customModel, lookup, areas)
        this.car_access_enc = lookup!!.getBooleanEncodedValue("car_access")
        this.road_environment_enc = lookup!!.getEnumEncodedValue("road_environment", RoadEnvironment::class.java)
        this.ferry_speed_enc = lookup!!.getDecimalEncodedValue("ferry_speed")
        this.car_average_speed_enc = lookup!!.getDecimalEncodedValue("car_average_speed")
        this.max_speed_enc = lookup!!.getDecimalEncodedValue("max_speed")
    }

    override fun getPriority(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 1.0
        val car_access: Boolean = if (reverse) edge.getReverse(this.car_access_enc) else edge.get(this.car_access_enc)
        if ((!car_access)) { value *= 0.0 }
        return value
    }

    override fun getSpeed(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 999.0
        val road_environment: RoadEnvironment = if (reverse) edge.getReverse(this.road_environment_enc) else edge.get(this.road_environment_enc)
        val ferry_speed: Double = if (reverse) edge.getReverse(this.ferry_speed_enc) else edge.get(this.ferry_speed_enc)
        val car_average_speed: Double = if (reverse) edge.getReverse(this.car_average_speed_enc) else edge.get(this.car_average_speed_enc)
        val max_speed: Double = if (reverse) edge.getReverse(this.max_speed_enc) else edge.get(this.max_speed_enc)
        if ((road_environment == RoadEnvironment.FERRY)) { value = kotlin.math.min(value, ferry_speed) }
        else { value = kotlin.math.min(value, car_average_speed) }
        if (true) { value = kotlin.math.min(value, (max_speed * 0.9)) }
        return value
    }

    override fun getTurnPenalty(graph: BaseGraph, edgeIntAccess: EdgeIntAccess, inEdge: Int, viaNode: Int, outEdge: Int): Double {
        var value = 0.0
        return value
    }
}
