// Generated by GraphHopper's CustomWeightingSourceGenerator - DO NOT EDIT.
// Semantics mirror the Janino runtime template of CustomModelParser (GraphHopper, Apache License 2.0).
// Register at app startup: GeneratedWeightingRegistry.register(customModel, ::GeneratedCarCustomWeighting)
package com.graphhopper.routing.weighting.custom.generate

import com.graphhopper.routing.ev.*
import com.graphhopper.routing.weighting.custom.CustomWeightingHelper
import com.graphhopper.storage.BaseGraph
import com.graphhopper.util.CustomModel
import com.graphhopper.util.EdgeIteratorState
import com.graphhopper.util.JsonFeature

class GeneratedCarCustomWeighting(
    customModel: CustomModel?, lookup: EncodedValueLookup?, areas: Map<String, JsonFeature>?
) : CustomWeightingHelper() {
    private val car_access_enc: BooleanEncodedValue = lookup!!.getBooleanEncodedValue("car_access")
    private val road_environment_enc: EnumEncodedValue<RoadEnvironment> = lookup!!.getEnumEncodedValue("road_environment", RoadEnvironment::class.java)
    private val ferry_speed_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("ferry_speed")
    private val car_average_speed_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("car_average_speed")
    private val max_speed_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("max_speed")

    init {
        init(customModel, lookup, areas)
    }

    override fun getPriority(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 1.0
        val car_access: Boolean = if (reverse) edge.getReverse(this.car_access_enc) else edge.get(this.car_access_enc)
        if ((!car_access)) { value *= 0.0 }
        return value
    }

    override fun getSpeed(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 999.0
        val road_environment: RoadEnvironment = if (reverse) edge.getReverse(this.road_environment_enc) else edge.get(this.road_environment_enc)
        val ferry_speed: Double = if (reverse) edge.getReverse(this.ferry_speed_enc) else edge.get(this.ferry_speed_enc)
        val car_average_speed: Double = if (reverse) edge.getReverse(this.car_average_speed_enc) else edge.get(this.car_average_speed_enc)
        val max_speed: Double = if (reverse) edge.getReverse(this.max_speed_enc) else edge.get(this.max_speed_enc)
        if ((road_environment == RoadEnvironment.FERRY)) { value = kotlin.math.min(value, ferry_speed) }
        else { value = kotlin.math.min(value, car_average_speed) }
        if (true) { value = kotlin.math.min(value, (max_speed * 0.9)) }
        return value
    }

    override fun getTurnPenalty(graph: BaseGraph, edgeIntAccess: EdgeIntAccess, inEdge: Int, viaNode: Int, outEdge: Int): Double {
        var value = 0.0
        return value
    }
}
