// Generated by GraphHopper's CustomWeightingSourceGenerator - DO NOT EDIT.
// Semantics mirror the Janino runtime template of CustomModelParser (GraphHopper, Apache License 2.0).
// Register at app startup: GeneratedWeightingRegistry.register(customModel, ::GeneratedKitchenSinkCustomWeighting)
package com.graphhopper.routing.weighting.custom.generate

import com.graphhopper.routing.ev.*
import com.graphhopper.routing.weighting.custom.CustomWeightingHelper
import com.graphhopper.storage.BaseGraph
import com.graphhopper.util.CustomModel
import com.graphhopper.util.EdgeIteratorState
import com.graphhopper.util.JsonFeature
import com.graphhopper.util.shapes.Polygon
import org.locationtech.jts.geom.Polygonal
import org.locationtech.jts.geom.prep.PreparedPolygon

class GeneratedKitchenSinkCustomWeighting(
    customModel: CustomModel?, lookup: EncodedValueLookup?, areas: Map<String, JsonFeature>?
) : CustomWeightingHelper() {
    private val car_access_enc: BooleanEncodedValue = lookup!!.getBooleanEncodedValue("car_access")
    private val road_class_enc: EnumEncodedValue<RoadClass> = lookup!!.getEnumEncodedValue("road_class", RoadClass::class.java)
    private val in_area_a: Polygon = Polygon(PreparedPolygon(areas!!["area_a"]!!.getGeometry() as Polygonal))
    private val hike_rating_enc: IntEncodedValue = lookup!!.getIntEncodedValue("hike_rating")
    private val country_enc: EnumEncodedValue<Country> = lookup!!.getEnumEncodedValue("country", Country::class.java)
    private val max_speed_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("max_speed")
    private val mtb_rating_enc: IntEncodedValue = lookup!!.getIntEncodedValue("mtb_rating")
    private val car_average_speed_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("car_average_speed")
    private val average_slope_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("average_slope")
    private val road_environment_enc: EnumEncodedValue<RoadEnvironment> = lookup!!.getEnumEncodedValue("road_environment", RoadEnvironment::class.java)
    private val roundabout_enc: BooleanEncodedValue = lookup!!.getBooleanEncodedValue("roundabout")
    private val orientation_enc: DecimalEncodedValue = lookup!!.getDecimalEncodedValue("orientation")

    init {
        init(customModel, lookup, areas)
    }

    override fun getPriority(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 1.0
        val backward_car_access: Boolean = if (reverse) edge.get(this.car_access_enc) else edge.getReverse(this.car_access_enc)
        val car_access: Boolean = if (reverse) edge.getReverse(this.car_access_enc) else edge.get(this.car_access_enc)
        val road_class: RoadClass = if (reverse) edge.getReverse(this.road_class_enc) else edge.get(this.road_class_enc)
        val hike_rating: Int = if (reverse) edge.getReverse(this.hike_rating_enc) else edge.get(this.hike_rating_enc)
        val country: Country = if (reverse) edge.getReverse(this.country_enc) else edge.get(this.country_enc)
        val max_speed: Double = if (reverse) edge.getReverse(this.max_speed_enc) else edge.get(this.max_speed_enc)
        val mtb_rating: Int = if (reverse) edge.getReverse(this.mtb_rating_enc) else edge.get(this.mtb_rating_enc)
        if ((backward_car_access != car_access)) { value *= 0.5 }
        if (((road_class == RoadClass.PRIMARY) || CustomWeightingHelper.`in`(this.in_area_a, edge))) { value *= 0.9 }
        else if (((road_class.ordinal > 5) && ((hike_rating shr 1) == 1))) { value *= 0.8 }
        if ((country.isRightHandTraffic && (country == Country.DEU))) { value *= 0.95 }
        if (((((((((65.0 < max_speed) && (31 > hike_rating)) && (5 > mtb_rating)) && (8.0 < max_speed)) && (10.0 < max_speed)) && (3L > hike_rating.toLong())) && (2.5 < max_speed)) && (10.0 < max_speed))) { value *= 0.99 }
        if ((true && ((hike_rating ushr 1) >= 1))) { value *= 0.98 }
        return value
    }

    override fun getSpeed(edge: EdgeIteratorState, reverse: Boolean): Double {
        var value = 999.0
        val car_average_speed: Double = if (reverse) edge.getReverse(this.car_average_speed_enc) else edge.get(this.car_average_speed_enc)
        val hike_rating: Int = if (reverse) edge.getReverse(this.hike_rating_enc) else edge.get(this.hike_rating_enc)
        val max_speed: Double = if (reverse) edge.getReverse(this.max_speed_enc) else edge.get(this.max_speed_enc)
        val average_slope: Double = if (reverse) edge.getReverse(this.average_slope_enc) else edge.get(this.average_slope_enc)
        val road_environment: RoadEnvironment = if (reverse) edge.getReverse(this.road_environment_enc) else edge.get(this.road_environment_enc)
        val roundabout: Boolean = if (reverse) edge.getReverse(this.roundabout_enc) else edge.get(this.roundabout_enc)
        if (true) { value = kotlin.math.min(value, car_average_speed) }
        if (((hike_rating / 2) == 1)) { value *= 0.5 }
        else if (((hike_rating and 1) == 0)) { value *= 0.8 }
        else { value *= 0.9 }
        if (((max_speed > 100.0) || (kotlin.math.abs(average_slope) > 2.0))) { value = kotlin.math.min(value, (kotlin.math.sqrt(max_speed) * 10.0)) }
        if ((road_environment == RoadEnvironment.FERRY)) {
            if (true) { value = kotlin.math.min(value, 30.0) }
            if (roundabout) { value *= 0.5 }
        }
        return value
    }

    override fun getTurnPenalty(graph: BaseGraph, edgeIntAccess: EdgeIntAccess, inEdge: Int, viaNode: Int, outEdge: Int): Double {
        var value = 0.0
        val inEdgeReverse = !graph.isAdjNode(inEdge, viaNode)
        val outEdgeReverse = graph.isAdjNode(outEdge, viaNode)
        val change_angle: Double = CustomWeightingHelper.calcChangeAngle(edgeIntAccess, this.orientation_enc, inEdge, inEdgeReverse, outEdge, !outEdgeReverse)
        val prev_road_class: RoadClass = this.road_class_enc.getEnum(inEdgeReverse, inEdge, edgeIntAccess)
        val road_class: RoadClass = this.road_class_enc.getEnum(outEdgeReverse, outEdge, edgeIntAccess)
        val street_name: String = graph.getEdgeIteratorState(outEdge, Int.MIN_VALUE)!!.name
        val prev_street_name: String = graph.getEdgeIteratorState(inEdge, Int.MIN_VALUE)!!.name
        val prev_max_speed: Double = this.max_speed_enc.getDecimal(inEdgeReverse, inEdge, edgeIntAccess)
        val car_average_speed: Double = this.car_average_speed_enc.getDecimal(outEdgeReverse, outEdge, edgeIntAccess)
        if (((change_angle > 25.0) && (prev_road_class == road_class))) { value += 3.0 }
        else if ((street_name === "Main St")) { value += 1.0 }
        else if ((street_name.contains("Main") || prev_street_name.equals(street_name))) { value += 5.5 }
        else if ((prev_max_speed > 50.0)) { value += (car_average_speed * 2.0) }
        else { value += Double.POSITIVE_INFINITY }
        return value
    }
}
