/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.graphhopper.util;

import com.graphhopper.util.NumHelper;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class NumHelper_DiffblueTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: NumHelper */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void compareInputZeroZeroOutputZero() {

    // Arrange
    final double d1 = 0.0;
    final double d2 = 0.0;

    // Act
    final int retval = NumHelper.compare(d1, d2);

    // Assert result
    Assert.assertEquals(0, retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 35 branch to line 35
   */

  @Test
  public void equalsInputZeroZeroOutputTrue() {

    // Arrange
    final double d1 = 0.0;
    final double d2 = 0.0;

    // Act
    final boolean retval = NumHelper.equals(d1, d2);

    // Assert result
    Assert.assertEquals(true, retval);
  }
}
