/*
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.graphhopper.util;

import com.graphhopper.util.GHUtility;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GHUtility_DiffblueTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: GHUtility */

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 373 branch to line 373
   */

  @Test
  public void reverseEdgeKeyInputPositiveOutputZero() {

    // Arrange
    final int edgeKey = 1;

    // Act
    final int retval = GHUtility.reverseEdgeKey(edgeKey);

    // Assert result
    Assert.assertEquals(0, retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 373 branch to line 373
   */

  @Test
  public void reverseEdgeKeyInputZeroOutputPositive() {

    // Arrange
    final int edgeKey = 0;

    // Act
    final int retval = GHUtility.reverseEdgeKey(edgeKey);

    // Assert result
    Assert.assertEquals(1, retval);
  }
}
